using System.Text;

namespace SqlBound.Generators;

/// <summary>
/// Emits the implementation part of one <c>[SqlQuery]</c> method from its
/// <see cref="QueryMethodModel"/>: straight-line <c>DbDataReader</c> code with ordinals resolved
/// once before the read loop, per-column <c>IsDBNull</c> handling, and no reflection.
/// </summary>
internal static class QueryMethodEmitter
{
    public static string GetHintName(QueryMethodModel model)
    {
        var builder = new StringBuilder();
        if (model.Namespace.Length > 0)
        {
            builder.Append(model.Namespace).Append('.');
        }

        foreach (var type in model.ContainingTypes)
        {
            builder.Append(type.Name).Append('.');
        }

        return builder
            .Append(model.MethodName).Append('.')
            .Append(SignatureHash(model))
            .Append(".g.cs")
            .ToString();
    }

    public static string EmitSource(QueryMethodModel model)
    {
        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n");
        builder.Append("// Emitted by the SqlBound source generator. Do not edit.\n");
        builder.Append("#nullable enable\n\n");
        if (model.Namespace.Length > 0)
        {
            builder.Append("namespace ").Append(model.Namespace).Append(";\n\n");
        }

        void Line(int level, string text)
        {
            if (text.Length > 0)
            {
                builder.Append(new string(' ', level * 4)).Append(text);
            }

            builder.Append('\n');
        }

        var depth = 0;
        foreach (var type in model.ContainingTypes)
        {
            Line(depth, $"partial {type.Keyword} {type.Name}");
            Line(depth, "{");
            depth++;
        }

        EmitMethod(model, depth, Line);

        for (var i = model.ContainingTypes.Count - 1; i >= 0; i--)
        {
            Line(i, "}");
        }

        return builder.ToString();
    }

    private static void EmitMethod(QueryMethodModel model, int depth, Action<int, string> line)
    {
        var connection = ParameterName(model, ParameterKind.Connection);
        var transaction = ParameterNameOrNull(model, ParameterKind.Transaction);
        var cancellationToken = ParameterNameOrNull(model, ParameterKind.CancellationToken)
            ?? "global::System.Threading.CancellationToken.None";

        var signatureParameters = new List<string>();
        foreach (var parameter in model.Parameters)
        {
            var prefix = model.IsExtensionMethod && signatureParameters.Count == 0 ? "this " : "";
            if (model.Shape == ResultShape.Stream && parameter.Kind == ParameterKind.CancellationToken)
            {
                prefix += "[global::System.Runtime.CompilerServices.EnumeratorCancellation] ";
            }

            signatureParameters.Add($"{prefix}{parameter.TypeText} {parameter.Name}");
        }

        line(depth, $"{model.Accessibility} static async partial {model.ReturnTypeText} "
            + $"{model.MethodName}({string.Join(", ", signatureParameters)})");
        line(depth, "{");
        line(depth + 1, $"if ({connection} is null)");
        line(depth + 1, "{");
        line(depth + 2, $"throw new global::System.ArgumentNullException(nameof({connection}));");
        line(depth + 1, "}");
        line(depth + 1, "");
        line(depth + 1, $"global::System.Data.Common.DbCommand __command = {connection}.CreateCommand();");
        line(depth + 1, "try");
        line(depth + 1, "{");
        line(depth + 2, $"__command.CommandText = @\"{model.CommandText.Replace("\"", "\"\"")}\";");
        if (transaction is not null)
        {
            line(depth + 2, $"__command.Transaction = {transaction};");
        }

        var scalarIndex = 0;
        foreach (var parameter in model.Parameters)
        {
            if (parameter.Kind != ParameterKind.Scalar)
            {
                continue;
            }

            var value = parameter.CanBeNull
                ? $"(object?){parameter.Name} ?? global::System.DBNull.Value"
                : parameter.Name;
            line(depth + 2, $"global::System.Data.Common.DbParameter __parameter{scalarIndex} = __command.CreateParameter();");
            line(depth + 2, $"__parameter{scalarIndex}.ParameterName = \"@{parameter.Name}\";");
            line(depth + 2, $"__parameter{scalarIndex}.Value = {value};");
            line(depth + 2, $"__command.Parameters.Add(__parameter{scalarIndex});");
            scalarIndex++;
        }

        if (model.Shape is ResultShape.Execute or ResultShape.ExecuteDiscard)
        {
            var keyword = model.Shape == ResultShape.Execute ? "return await" : "await";
            line(depth + 2, $"{keyword} __command.ExecuteNonQueryAsync({cancellationToken}).ConfigureAwait(false);");
        }
        else
        {
            EmitReaderBlock(model, depth, line, cancellationToken);
        }

        line(depth + 1, "}");
        line(depth + 1, "finally");
        line(depth + 1, "{");
        line(depth + 2, "await __command.DisposeAsync().ConfigureAwait(false);");
        line(depth + 1, "}");
        line(depth, "}");
    }

    private static void EmitReaderBlock(
        QueryMethodModel model, int depth, Action<int, string> line, string cancellationToken)
    {
        line(depth + 2, "global::System.Data.Common.DbDataReader __reader = "
            + $"await __command.ExecuteReaderAsync({cancellationToken}).ConfigureAwait(false);");
        line(depth + 2, "try");
        line(depth + 2, "{");
        if (model.ElementKind == ResultElementKind.Row)
        {
            for (var i = 0; i < model.Columns.Count; i++)
            {
                line(depth + 3, $"int __ordinal{i} = __reader.GetOrdinal(\"{model.Columns[i].Name}\");");
            }
        }

        switch (model.Shape, model.ElementKind)
        {
            case (ResultShape.RowList, ResultElementKind.Row):
                EmitRowListRead(model, depth + 3, line, cancellationToken);
                break;
            case (ResultShape.RowList, ResultElementKind.Scalar):
                EmitScalarListRead(model, depth + 3, line, cancellationToken);
                break;
            case (ResultShape.SingleRow, ResultElementKind.Row):
                EmitSingleRead(model, depth + 3, line, cancellationToken, optional: false);
                break;
            case (ResultShape.OptionalRow, ResultElementKind.Row):
                EmitSingleRead(model, depth + 3, line, cancellationToken, optional: true);
                break;
            case (ResultShape.SingleRow, ResultElementKind.Scalar):
                EmitScalarSingleRead(model, depth + 3, line, cancellationToken, optional: false);
                break;
            case (ResultShape.OptionalRow, ResultElementKind.Scalar):
                EmitScalarSingleRead(model, depth + 3, line, cancellationToken, optional: true);
                break;
            case (ResultShape.Stream, _):
                EmitStreamRead(model, depth + 3, line, cancellationToken);
                break;
            default:
                throw new InvalidOperationException(
                    $"Unknown result shape '{model.Shape}'/'{model.ElementKind}'.");
        }

        line(depth + 2, "}");
        line(depth + 2, "finally");
        line(depth + 2, "{");
        line(depth + 3, "await __reader.DisposeAsync().ConfigureAwait(false);");
        line(depth + 2, "}");
    }

    private static void EmitRowListRead(
        QueryMethodModel model, int depth, Action<int, string> line, string cancellationToken)
    {
        line(depth, $"global::System.Collections.Generic.List<{model.RowTypeText}> __rows = new();");
        line(depth, $"while (await __reader.ReadAsync({cancellationToken}).ConfigureAwait(false))");
        line(depth, "{");
        EmitRowConstruction(model, depth + 1, line, "__rows.Add(", ");");
        line(depth, "}");
        line(depth, "");
        line(depth, "return __rows;");
    }

    private static void EmitSingleRead(
        QueryMethodModel model, int depth, Action<int, string> line, string cancellationToken, bool optional)
    {
        line(depth, $"if (!await __reader.ReadAsync({cancellationToken}).ConfigureAwait(false))");
        line(depth, "{");
        line(depth + 1, optional
            ? "return null;"
            : "throw new global::System.InvalidOperationException("
                + "\"The query returned no rows but exactly one was expected.\");");
        line(depth, "}");
        line(depth, "");
        EmitRowConstruction(model, depth, line, $"{model.RowTypeText} __row = ", ";");
        line(depth, $"if (await __reader.ReadAsync({cancellationToken}).ConfigureAwait(false))");
        line(depth, "{");
        line(depth + 1, "throw new global::System.InvalidOperationException("
            + $"\"The query returned more than one row but {(optional ? "at most" : "exactly")} one was expected.\");");
        line(depth, "}");
        line(depth, "");
        line(depth, "return __row;");
    }

    private static void EmitStreamRead(
        QueryMethodModel model, int depth, Action<int, string> line, string cancellationToken)
    {
        line(depth, $"while (await __reader.ReadAsync({cancellationToken}).ConfigureAwait(false))");
        line(depth, "{");
        if (model.ElementKind == ResultElementKind.Scalar)
        {
            line(depth + 1, $"yield return {ReadScalar(model.Columns[0])};");
        }
        else
        {
            EmitRowConstruction(model, depth + 1, line, "yield return ", ";");
        }

        line(depth, "}");
    }

    private static void EmitScalarListRead(
        QueryMethodModel model, int depth, Action<int, string> line, string cancellationToken)
    {
        line(depth, $"global::System.Collections.Generic.List<{model.RowTypeText}> __rows = new();");
        line(depth, $"while (await __reader.ReadAsync({cancellationToken}).ConfigureAwait(false))");
        line(depth, "{");
        line(depth + 1, $"__rows.Add({ReadScalar(model.Columns[0])});");
        line(depth, "}");
        line(depth, "");
        line(depth, "return __rows;");
    }

    private static void EmitScalarSingleRead(
        QueryMethodModel model, int depth, Action<int, string> line, string cancellationToken, bool optional)
    {
        line(depth, $"if (!await __reader.ReadAsync({cancellationToken}).ConfigureAwait(false))");
        line(depth, "{");
        line(depth + 1, optional
            ? "return null;"
            : "throw new global::System.InvalidOperationException("
                + "\"The query returned no rows but a scalar value was expected.\");");
        line(depth, "}");
        line(depth, "");
        line(depth, $"return {ReadScalar(model.Columns[0])};");
    }

    private static string ReadScalar(ColumnModel column)
    {
        var read = $"__reader.{column.GetterInvocation}(0)";
        if (column.IsNullable)
        {
            return $"__reader.IsDBNull(0) ? default({column.TypeText}) : {read}";
        }

        return "__reader.IsDBNull(0) "
            + "? throw new global::System.InvalidOperationException("
            + $"\"The scalar result is NULL but maps to non-nullable '{column.TypeText}'.\") "
            + $": {read}";
    }

    private static void EmitRowConstruction(
        QueryMethodModel model, int depth, Action<int, string> line, string prefix, string suffix)
    {
        line(depth, $"{prefix}new {model.RowTypeText}(");
        for (var i = 0; i < model.Columns.Count; i++)
        {
            var terminator = i == model.Columns.Count - 1 ? ")" + suffix : ",";
            line(depth + 1, ReadColumn(model.Columns[i], i) + terminator);
        }
    }

    private static string ReadColumn(ColumnModel column, int index)
    {
        var read = $"__reader.{column.GetterInvocation}(__ordinal{index})";
        if (column.IsNullable)
        {
            return $"__reader.IsDBNull(__ordinal{index}) ? default({column.TypeText}) : {read}";
        }

        return $"__reader.IsDBNull(__ordinal{index}) "
            + "? throw new global::System.InvalidOperationException("
            + $"\"Column '{column.Name}' is NULL but maps to non-nullable '{column.TypeText}'.\") "
            + $": {read}";
    }

    private static string ParameterName(QueryMethodModel model, ParameterKind kind) =>
        ParameterNameOrNull(model, kind)
        ?? throw new InvalidOperationException($"The model has no {kind} parameter.");

    private static string? ParameterNameOrNull(QueryMethodModel model, ParameterKind kind)
    {
        foreach (var parameter in model.Parameters)
        {
            if (parameter.Kind == kind)
            {
                return parameter.Name;
            }
        }

        return null;
    }

    private static string SignatureHash(QueryMethodModel model)
    {
        var signature = new StringBuilder(model.MethodName);
        foreach (var parameter in model.Parameters)
        {
            signature.Append(',').Append(parameter.TypeText);
        }

        // FNV-1a: deterministic across processes, unlike string.GetHashCode, so the hint name
        // (and with it the generated output) is stable build over build.
        var hash = 2166136261u;
        foreach (var character in signature.ToString())
        {
            hash = unchecked((hash ^ character) * 16777619u);
        }

        return hash.ToString("x8");
    }
}
