using Microsoft.CodeAnalysis;

namespace SqlBound.Generators.UnitTests;

public class QueryMethodEmissionTests
{
    private const string Prelude = """
        using System.Collections.Generic;
        using System.Data.Common;
        using System.Threading;
        using System.Threading.Tasks;
        using SqlBound;

        namespace App;

        public sealed record Item(int Id, string Name, decimal? Price);

        """;

    private const string CanonicalSource = Prelude + """
        public static partial class ItemQueries
        {
            [SqlQuery("SELECT id, name, price FROM items WHERE category = @category")]
            public static partial Task<IReadOnlyList<Item>> GetItemsAsync(
                DbConnection connection,
                DbTransaction? transaction,
                string category,
                CancellationToken cancellationToken = default);
        }
        """;

    private const string SingleRowSource = Prelude + """
        public static partial class ItemQueries
        {
            [SqlQuery("SELECT id, name, price FROM items WHERE id = @id")]
            public static partial Task<Item> GetByIdAsync(
                DbConnection connection, int id, CancellationToken cancellationToken = default);
        }
        """;

    private const string OptionalRowSource = Prelude + """
        public static partial class ItemQueries
        {
            [SqlQuery("SELECT id, name, price FROM items WHERE id = @id")]
            public static partial Task<Item?> FindByIdAsync(
                DbConnection connection, int id, CancellationToken cancellationToken = default);
        }
        """;

    [Fact]
    public void Should_EmitStrictSingleReadImplementation_When_ReturnTypeIsTaskOfRow()
    {
        var outcome = GeneratorHarness.Run(SingleRowSource);

        AssertCompilesClean(outcome);
        var generated = Assert.Single(outcome.GeneratedSources).SourceText.ToString();
        Assert.Contains("no rows but exactly one was expected", generated);
        Assert.Contains("more than one row", generated);
    }

    [Fact]
    public void Should_MatchExpectedSource_When_SingleRowQueryIsGenerated()
    {
        const string expected = """
            // <auto-generated/>
            // Emitted by the SqlBound source generator. Do not edit.
            #nullable enable

            namespace App;

            partial class ItemQueries
            {
                public static async partial global::System.Threading.Tasks.Task<global::App.Item> GetByIdAsync(global::System.Data.Common.DbConnection connection, int id, global::System.Threading.CancellationToken cancellationToken)
                {
                    if (connection is null)
                    {
                        throw new global::System.ArgumentNullException(nameof(connection));
                    }

                    global::System.Data.Common.DbCommand __command = connection.CreateCommand();
                    try
                    {
                        __command.CommandText = @"SELECT id, name, price FROM items WHERE id = @id";
                        global::System.Data.Common.DbParameter __parameter0 = __command.CreateParameter();
                        __parameter0.ParameterName = "@id";
                        __parameter0.Value = id;
                        __command.Parameters.Add(__parameter0);
                        global::System.Data.Common.DbDataReader __reader = await __command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);
                        try
                        {
                            int __ordinal0 = __reader.GetOrdinal("Id");
                            int __ordinal1 = __reader.GetOrdinal("Name");
                            int __ordinal2 = __reader.GetOrdinal("Price");
                            if (!await __reader.ReadAsync(cancellationToken).ConfigureAwait(false))
                            {
                                throw new global::System.InvalidOperationException("The query returned no rows but exactly one was expected.");
                            }

                            global::App.Item __row = new global::App.Item(
                                __reader.IsDBNull(__ordinal0) ? throw new global::System.InvalidOperationException("Column 'Id' is NULL but maps to non-nullable 'int'.") : __reader.GetInt32(__ordinal0),
                                __reader.IsDBNull(__ordinal1) ? throw new global::System.InvalidOperationException("Column 'Name' is NULL but maps to non-nullable 'string'.") : __reader.GetString(__ordinal1),
                                __reader.IsDBNull(__ordinal2) ? default(decimal?) : __reader.GetDecimal(__ordinal2));
                            if (await __reader.ReadAsync(cancellationToken).ConfigureAwait(false))
                            {
                                throw new global::System.InvalidOperationException("The query returned more than one row but exactly one was expected.");
                            }

                            return __row;
                        }
                        finally
                        {
                            await __reader.DisposeAsync().ConfigureAwait(false);
                        }
                    }
                    finally
                    {
                        await __command.DisposeAsync().ConfigureAwait(false);
                    }
                }
            }

            """;

        var outcome = GeneratorHarness.Run(SingleRowSource);

        var generated = Assert.Single(outcome.GeneratedSources);
        Assert.Equal("App.ItemQueries.GetByIdAsync.a1de9431.g.cs", generated.HintName);
        Assert.Equal(expected, generated.SourceText.ToString());
    }

    [Fact]
    public void Should_ReturnNullInsteadOfThrowing_When_ReturnTypeIsTaskOfNullableRow()
    {
        var outcome = GeneratorHarness.Run(OptionalRowSource);

        AssertCompilesClean(outcome);
        var generated = Assert.Single(outcome.GeneratedSources).SourceText.ToString();
        Assert.Contains("return null;", generated);
        Assert.Contains("more than one row", generated);
        Assert.DoesNotContain("no rows but exactly one was expected", generated);
    }

    [Fact]
    public void Should_EmitCompilableImplementation_When_OptionalRowTypeIsValueType()
    {
        const string source = Prelude + """
            public readonly record struct Point(double X, double Y);

            public static partial class PointQueries
            {
                [SqlQuery("SELECT x, y FROM points WHERE id = @id")]
                public static partial Task<Point?> FindAsync(
                    DbConnection connection, int id, CancellationToken cancellationToken = default);
            }
            """;

        var outcome = GeneratorHarness.Run(source);

        AssertCompilesClean(outcome);
    }

    [Fact]
    public void Should_EmitFirstColumnScalarRead_When_ReturnTypeIsTaskOfScalar()
    {
        const string source = Prelude + """
            public static partial class ItemQueries
            {
                [SqlQuery("SELECT COUNT(*) FROM items")]
                public static partial Task<int> CountAsync(
                    DbConnection connection, CancellationToken cancellationToken = default);
            }
            """;

        var outcome = GeneratorHarness.Run(source);

        AssertCompilesClean(outcome);
        var generated = Assert.Single(outcome.GeneratedSources).SourceText.ToString();
        Assert.Contains("GetInt32(0)", generated);
        Assert.Contains("no rows but a scalar value was expected", generated);
    }

    [Fact]
    public void Should_ReturnNullOnNoRowsOrDbNull_When_ReturnTypeIsTaskOfNullableScalar()
    {
        const string source = Prelude + """
            public static partial class ItemQueries
            {
                [SqlQuery("SELECT MAX(price) FROM items")]
                public static partial Task<decimal?> MaxPriceAsync(
                    DbConnection connection, CancellationToken cancellationToken = default);
            }
            """;

        var outcome = GeneratorHarness.Run(source);

        AssertCompilesClean(outcome);
        var generated = Assert.Single(outcome.GeneratedSources).SourceText.ToString();
        Assert.Contains("return null;", generated);
        Assert.Contains("default(decimal?)", generated);
        Assert.Contains("GetDecimal(0)", generated);
    }

    [Fact]
    public void Should_EmitScalarList_When_ReturnTypeIsTaskOfReadOnlyListOfScalar()
    {
        const string source = Prelude + """
            public static partial class ItemQueries
            {
                [SqlQuery("SELECT name FROM items")]
                public static partial Task<IReadOnlyList<string>> GetNamesAsync(
                    DbConnection connection, CancellationToken cancellationToken = default);
            }
            """;

        var outcome = GeneratorHarness.Run(source);

        AssertCompilesClean(outcome);
        var generated = Assert.Single(outcome.GeneratedSources).SourceText.ToString();
        Assert.Contains("List<string> __rows", generated);
        Assert.Contains("GetString(0)", generated);
    }

    [Fact]
    public void Should_EmitCompilableImplementation_When_ScalarListElementIsNullable()
    {
        const string source = Prelude + """
            public static partial class ItemQueries
            {
                [SqlQuery("SELECT price FROM items")]
                public static partial Task<IReadOnlyList<decimal?>> GetPricesAsync(
                    DbConnection connection, CancellationToken cancellationToken = default);
            }
            """;

        var outcome = GeneratorHarness.Run(source);

        AssertCompilesClean(outcome);
        var generated = Assert.Single(outcome.GeneratedSources).SourceText.ToString();
        Assert.Contains("List<decimal?> __rows", generated);
        Assert.Contains("default(decimal?)", generated);
    }

    [Fact]
    public void Should_EmitAsyncIteratorWithEnumeratorCancellation_When_ReturnTypeIsAsyncEnumerableOfRow()
    {
        const string source = Prelude + """
            public static partial class ItemQueries
            {
                [SqlQuery("SELECT id, name, price FROM items")]
                public static partial IAsyncEnumerable<Item> StreamAsync(
                    DbConnection connection, CancellationToken cancellationToken = default);
            }
            """;

        var outcome = GeneratorHarness.Run(source);

        AssertCompilesClean(outcome);
        var generated = Assert.Single(outcome.GeneratedSources).SourceText.ToString();
        Assert.Contains("yield return new global::App.Item(", generated);
        Assert.Contains("[global::System.Runtime.CompilerServices.EnumeratorCancellation]", generated);
    }

    [Fact]
    public void Should_EmitCompilableIterator_When_ReturnTypeIsAsyncEnumerableOfScalar()
    {
        const string source = Prelude + """
            public static partial class ItemQueries
            {
                [SqlQuery("SELECT name FROM items")]
                public static partial IAsyncEnumerable<string> StreamNamesAsync(
                    DbConnection connection, CancellationToken cancellationToken = default);
            }
            """;

        var outcome = GeneratorHarness.Run(source);

        AssertCompilesClean(outcome);
        var generated = Assert.Single(outcome.GeneratedSources).SourceText.ToString();
        Assert.Contains("GetString(0)", generated);
        Assert.Contains("yield return", generated);
    }

    [Fact]
    public void Should_EmitCompilableIterator_When_StreamHasNoCancellationToken()
    {
        const string source = Prelude + """
            public static partial class ItemQueries
            {
                [SqlQuery("SELECT id, name, price FROM items")]
                public static partial IAsyncEnumerable<Item> StreamAsync(DbConnection connection);
            }
            """;

        var outcome = GeneratorHarness.Run(source);

        AssertCompilesClean(outcome);
        var generated = Assert.Single(outcome.GeneratedSources).SourceText.ToString();
        Assert.DoesNotContain("EnumeratorCancellation", generated);
    }

    [Fact]
    public void Should_EmitSingleImplementationFile_When_MethodIsWellFormed()
    {
        var outcome = GeneratorHarness.Run(CanonicalSource);

        var generated = Assert.Single(outcome.GeneratedSources);
        Assert.StartsWith("App.ItemQueries.GetItemsAsync.", generated.HintName);
        Assert.EndsWith(".g.cs", generated.HintName);
    }

    [Fact]
    public void Should_EmitCompilableImplementation_When_MethodIsWellFormed()
    {
        var outcome = GeneratorHarness.Run(CanonicalSource);

        AssertCompilesClean(outcome);
    }

    [Fact]
    public void Should_MatchExpectedSource_When_CanonicalQueryIsGenerated()
    {
        const string expected = """
            // <auto-generated/>
            // Emitted by the SqlBound source generator. Do not edit.
            #nullable enable

            namespace App;

            partial class ItemQueries
            {
                public static async partial global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<global::App.Item>> GetItemsAsync(global::System.Data.Common.DbConnection connection, global::System.Data.Common.DbTransaction? transaction, string category, global::System.Threading.CancellationToken cancellationToken)
                {
                    if (connection is null)
                    {
                        throw new global::System.ArgumentNullException(nameof(connection));
                    }

                    global::System.Data.Common.DbCommand __command = connection.CreateCommand();
                    try
                    {
                        __command.CommandText = @"SELECT id, name, price FROM items WHERE category = @category";
                        __command.Transaction = transaction;
                        global::System.Data.Common.DbParameter __parameter0 = __command.CreateParameter();
                        __parameter0.ParameterName = "@category";
                        __parameter0.Value = (object?)category ?? global::System.DBNull.Value;
                        __command.Parameters.Add(__parameter0);
                        global::System.Data.Common.DbDataReader __reader = await __command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);
                        try
                        {
                            int __ordinal0 = __reader.GetOrdinal("Id");
                            int __ordinal1 = __reader.GetOrdinal("Name");
                            int __ordinal2 = __reader.GetOrdinal("Price");
                            global::System.Collections.Generic.List<global::App.Item> __rows = new();
                            while (await __reader.ReadAsync(cancellationToken).ConfigureAwait(false))
                            {
                                __rows.Add(new global::App.Item(
                                    __reader.IsDBNull(__ordinal0) ? throw new global::System.InvalidOperationException("Column 'Id' is NULL but maps to non-nullable 'int'.") : __reader.GetInt32(__ordinal0),
                                    __reader.IsDBNull(__ordinal1) ? throw new global::System.InvalidOperationException("Column 'Name' is NULL but maps to non-nullable 'string'.") : __reader.GetString(__ordinal1),
                                    __reader.IsDBNull(__ordinal2) ? default(decimal?) : __reader.GetDecimal(__ordinal2)));
                            }

                            return __rows;
                        }
                        finally
                        {
                            await __reader.DisposeAsync().ConfigureAwait(false);
                        }
                    }
                    finally
                    {
                        await __command.DisposeAsync().ConfigureAwait(false);
                    }
                }
            }

            """;

        var outcome = GeneratorHarness.Run(CanonicalSource);

        var generated = Assert.Single(outcome.GeneratedSources);
        Assert.Equal("App.ItemQueries.GetItemsAsync.a9dfc0d7.g.cs", generated.HintName);
        Assert.Equal(expected, generated.SourceText.ToString());
    }

    [Fact]
    public void Should_ResolveOrdinalsOnceAndGuardNulls_When_RowHasNullableAndNonNullableColumns()
    {
        var outcome = GeneratorHarness.Run(CanonicalSource);

        var source = Assert.Single(outcome.GeneratedSources).SourceText.ToString();
        Assert.Contains("""GetOrdinal("Id")""", source);
        Assert.Contains("""GetOrdinal("Name")""", source);
        Assert.Contains("""GetOrdinal("Price")""", source);
        Assert.Contains("default(decimal?)", source);
        Assert.Contains("InvalidOperationException", source);
    }

    [Fact]
    public void Should_BindEachScalarParameter_When_MethodHasMultipleScalars()
    {
        const string source = Prelude + """
            public static partial class ItemQueries
            {
                [SqlQuery("SELECT id, name, price FROM items WHERE name = @name AND id > @minimumId")]
                public static partial Task<IReadOnlyList<Item>> SearchAsync(
                    DbConnection connection, string name, int minimumId);
            }
            """;

        var outcome = GeneratorHarness.Run(source);

        AssertCompilesClean(outcome);
        var generated = Assert.Single(outcome.GeneratedSources).SourceText.ToString();
        Assert.Contains("""ParameterName = "@name";""", generated);
        Assert.Contains("""ParameterName = "@minimumId";""", generated);
    }

    [Fact]
    public void Should_UseCancellationTokenNone_When_MethodHasNoCancellationTokenParameter()
    {
        const string source = Prelude + """
            public static partial class ItemQueries
            {
                [SqlQuery("SELECT id, name, price FROM items")]
                public static partial Task<IReadOnlyList<Item>> GetAllAsync(DbConnection connection);
            }
            """;

        var outcome = GeneratorHarness.Run(source);

        AssertCompilesClean(outcome);
        var generated = Assert.Single(outcome.GeneratedSources).SourceText.ToString();
        Assert.Contains("CancellationToken.None", generated);
    }

    [Fact]
    public void Should_OmitTransactionAssignment_When_MethodHasNoTransactionParameter()
    {
        const string source = Prelude + """
            public static partial class ItemQueries
            {
                [SqlQuery("SELECT id, name, price FROM items")]
                public static partial Task<IReadOnlyList<Item>> GetAllAsync(DbConnection connection);
            }
            """;

        var outcome = GeneratorHarness.Run(source);

        AssertCompilesClean(outcome);
        var generated = Assert.Single(outcome.GeneratedSources).SourceText.ToString();
        Assert.DoesNotContain(".Transaction =", generated);
    }

    [Fact]
    public void Should_EmitCompilableImplementation_When_ContainingTypesAreNested()
    {
        const string source = Prelude + """
            public static partial class Data
            {
                public static partial class ItemQueries
                {
                    [SqlQuery("SELECT id, name, price FROM items")]
                    public static partial Task<IReadOnlyList<Item>> GetAllAsync(DbConnection connection);
                }
            }
            """;

        var outcome = GeneratorHarness.Run(source);

        AssertCompilesClean(outcome);
        var generated = Assert.Single(outcome.GeneratedSources);
        Assert.StartsWith("App.Data.ItemQueries.GetAllAsync.", generated.HintName);
    }

    [Fact]
    public void Should_EmitCompilableImplementation_When_RowUsesAllSupportedColumnTypes()
    {
        const string source = Prelude + """
            public sealed record Wide(
                int A, long B, short C, byte D, bool E, string F, double G, float H,
                decimal I, System.DateTime J, System.Guid K, byte[] L, int? M, string? N);

            public static partial class WideQueries
            {
                [SqlQuery("SELECT * FROM wide")]
                public static partial Task<IReadOnlyList<Wide>> GetAllAsync(DbConnection connection);
            }
            """;

        var outcome = GeneratorHarness.Run(source);

        AssertCompilesClean(outcome);
    }

    private static void AssertCompilesClean(GeneratorRunOutcome outcome)
    {
        Assert.Empty(outcome.GeneratorDiagnostics);
        Assert.DoesNotContain(outcome.CompilationDiagnostics, d => d.Severity >= DiagnosticSeverity.Warning);
    }
}
